import { chromium } from 'playwright';
const URL = process.argv[2];
const b = await chromium.launch({ headless:true, args:['--use-angle=metal','--ignore-gpu-blocklist','--mute-audio'] });
const p = await b.newPage({ viewport:{width:1600,height:900} });
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>m.type()==='error'&&errs.push(m.text()));
const t0=Date.now();
const resp = await p.goto(URL,{waitUntil:'domcontentloaded',timeout:60000});
await p.waitForFunction('window.__READY__===true',null,{timeout:90000});
const bootMs = Date.now()-t0;
await p.evaluate(()=>window.__APPLY_SHOT__('hero'));
await p.evaluate(()=>new Promise(d=>{let i=0;const t=()=>++i>=90?d():requestAnimationFrame(t);requestAnimationFrame(t)}));
await p.screenshot({path:'shots/live-verify.png'});
const info = await p.evaluate(()=>window.__RENDER_INFO__);
console.log(JSON.stringify({url:URL, http:resp.status(), bootMs, ready:true, calls:info.calls, tris:info.tris, errors:errs.slice(0,6)},null,2));
await b.close();
